#!/bin/csh

python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr2.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr2.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr2.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr3.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr3.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr3.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr4.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr4.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr4.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr5.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr5.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr5.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr6.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr6.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr6.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr7.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr7.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr7.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr8.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr8.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr8.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr9.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr9.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr9.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr10.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr10.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr10.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr11.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr11.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr11.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr12.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr12.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr12.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr13.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr13.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr13.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr14.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr14.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr14.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr15.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr15.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr15.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr16.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr16.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr16.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr17.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr17.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr17.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr18.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr18.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr18.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr19.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr19.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr19.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr20.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr20.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr20.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr21.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr21.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr21.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chr22.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chr22.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chr22.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chrX.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chrX.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chrX.txt junk.txt
python vcf_query_mongo_ACMG.py /gpfs/group/stsi/data/wellderly/CG_data/CG_chromosome/master2013_02_08_PASS_QC_hwe_CEU_noRel_snpEff_chrY.vcf.gz /gpfs/home/gerikson/wellderly_ACMG/Oct4th/SUMMARY_chrY.txt /gpfs/home/gerikson/wellderly_ACMG/Oct4th/notfound_chrY.txt junk.txt
