#!/bin/csh

python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr2.snps_indels.vars chr2_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr2_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr3.snps_indels.vars chr3_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr3_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr4.snps_indels.vars chr4_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr4_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr5.snps_indels.vars chr5_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr5_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr6.snps_indels.vars chr6_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr6_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr7.snps_indels.vars chr7_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr7_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr8.snps_indels.vars chr8_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr8_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr9.snps_indels.vars chr9_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr9_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr10.snps_indels.vars chr10_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr10_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr11.snps_indels.vars chr11_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr11_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr12.snps_indels.vars chr12_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr12_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr13.snps_indels.vars chr13_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr13_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr14.snps_indels.vars chr14_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr14_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr15.snps_indels.vars chr15_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr15_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr16.snps_indels.vars chr16_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr16_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr17.snps_indels.vars chr17_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr17_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr18.snps_indels.vars chr18_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr18_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr19.snps_indels.vars chr19_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr19_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr20.snps_indels.vars chr20_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr20_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr21.snps_indels.vars chr21_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr21_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chr22.snps_indels.vars chr22_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chr22_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chrX.snps_indels.vars chrX_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chrX_tabix_final.txt
python compare_allele_to_existing_tabix.NHLBI.py /gpfs/group/stsi/methods/annotation/sg-adviser/NHLBI/second_try/ESP6500SI.chrY.snps_indels.vars chrY_tabix_new.txt /gpfs/home/gerikson/wellderly/alleleFreq/PrefilterVCF/tabix/tabixFinal/chrY_tabix_final.txt